# Generated by Django 3.2.3 on 2021-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=20)),
                ('mail', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=20)),
                ('fono', models.IntegerField(max_length=20)),
                ('passwd', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
