# Generated by Django 3.1.3 on 2021-07-01 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bioequivalente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bioequivalente', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'bioequivalente',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
                ('precio', models.IntegerField()),
                ('url', models.ImageField(default='not_found', upload_to='')),
                ('stock', models.IntegerField(default=0)),
                ('bioequivalente', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.bioequivalente')),
            ],
            options={
                'db_table': 'medicamento',
            },
        ),
    ]
