# Generated by Django 3.2.3 on 2021-05-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210527_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fono',
        ),
        migrations.AlterField(
            model_name='user',
            name='mail',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='rut',
            field=models.CharField(max_length=9),
        ),
    ]
